# Generated by Django 3.0.5 on 2020-06-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200606_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='patronimic',
            new_name='patronymic',
        ),
        migrations.AlterField(
            model_name='resource',
            name='soft',
            field=models.ManyToManyField(related_name='soft', to='api.Soft'),
        ),
    ]
